vaadin.launch-browser=true
server.port=6969
spring.application.name=maintainsoft
spring.main.application-startup=buffering
spring.main.lazy-initialization=true
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,\
org.springframework.boot.autoconfigure.aop.AopAutoConfiguration
management.endpoints.web.exposure.include=health,info,startup,conditions

jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator

spring.datasource.url=jdbc:postgresql://msi.leo-blenny.ts.net/learning
spring.datasource.username=dharun
spring.datasource.password=ENC(tWk7ZWtYeJ4WXoiqnrlZFf2uaW2uvr5INNxA+qL45OcpD8krRchgbhw4zd84ZFNd)
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=none
jasypt.encryptor.password=mypass
jasypt.encryptor.key-obtention-iterations=1000
jasypt.encryptor.pool-size=1

logging.level.org.springframework.web=INFO
logging.level.root=INFO
logging.level.org.springframework=INFO

springdoc.swagger-ui.path=/swagger/ui
springdoc.api-docs.enabled=true