vaadin.launch-browser=true
server.port=8081
spring.application.name=maintainsoft


spring.datasource.url=jdbc:postgresql://msi.leo-blenny.ts.net/learning
spring.datasource.username=Dharun
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update