create table departments (deleted boolean not null, created_at timestamp(6) with time zone not null, poc_number bigint not null, updated_at timestamp(6) with time zone not null, version bigint, id uuid not null, created_by varchar(255) not null, dept_name varchar(255) not null unique, poc_name varchar(255) not null, updated_by varchar(255) not null, primary key (id));
create table machines (deleted boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, version bigint, department_id uuid not null, id uuid not null, created_by varchar(255) not null, name varchar(255) not null, serial_number varchar(255) not null, status varchar(255) not null check ((status in ('OPERATIONAL','UNDER_MAINTENANCE','DECOMMISSIONED'))), updated_by varchar(255) not null, primary key (id), unique (serial_number));
create table repair_spares (used_quantity integer not null, repair_id uuid not null, spare_id uuid not null, primary key (repair_id, spare_id));
create table repair_updates (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, repair_id uuid not null, description varchar(2000) not null, created_by varchar(255) not null, repair_status varchar(255) not null check ((repair_status in ('OPEN','IN_PROGRESS','COMPLETED'))), updated_by varchar(255) not null, primary key (id));
create table repairs (created_at timestamp(6) with time zone not null, end_date timestamp(6) with time zone, start_date timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, version bigint, id uuid not null, machine_id uuid not null, technician_id uuid, description varchar(1000) not null, created_by varchar(255) not null, idempotency_key varchar(255) not null unique, repair_priority varchar(255) not null check ((repair_priority in ('HIGH','LOW','NORMAL'))), repair_status varchar(255) not null check ((repair_status in ('OPEN','IN_PROGRESS','COMPLETED'))), repair_type varchar(255) not null check ((repair_type in ('PREVENTIVE','BREAKDOWN','SCHEDULED'))), updated_by varchar(255) not null, primary key (id));
create table spares (cost numeric(19,4), deleted boolean not null, stock integer not null, created_at timestamp(6) with time zone not null, last_purchase_date timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, version bigint, id uuid not null, created_by varchar(255) not null, name varchar(255), part_number varchar(255) unique, updated_by varchar(255) not null, primary key (id));
create table technicians (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, created_by varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, updated_by varchar(255) not null, primary key (id));
create table users (deleted boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, version bigint, department_id uuid, id uuid not null, created_by varchar(255) not null, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, phone varchar(255) not null unique, role varchar(255) check ((role in ('MANAGER','SUPERVISOR'))), updated_by varchar(255) not null, primary key (id), unique (email));
create index idx_machine_department on machines (department_id);
create index idx_machine_status on machines (status);
create index idx_machine_serial on machines (serial_number);
create index idx_repair_update_repair on repair_updates (repair_id);
create index idx_machine_repair on repairs (machine_id);
create index idx_repair_status on repairs (repair_status);
create index idx_repair_priority on repairs (repair_priority);
create index idx_repair_created on repairs (created_at);
create index idx_spare_part_number on spares (part_number);
create index idx_spare_quantity on spares (stock);
create index idx_user_email on users (email);
alter table if exists machines add constraint FKopkvjwk542pv6tobfgmmnph6g foreign key (department_id) references departments;
alter table if exists repair_spares add constraint FK8wk1drtvcprwar3h399dl7t5t foreign key (repair_id) references repairs;
alter table if exists repair_spares add constraint FK61yyf1pqj0k8d1sudo7hb516y foreign key (spare_id) references spares;
alter table if exists repair_updates add constraint FKbqfi0f07ihvcmlida7hpe6a8d foreign key (repair_id) references repairs;
alter table if exists repairs add constraint FKtra5slw998kc63441a9ttgv0l foreign key (machine_id) references machines;
alter table if exists repairs add constraint FKll7ggfytef29cb11aluhui9ja foreign key (technician_id) references technicians;
alter table if exists users add constraint FKsbg59w8q63i0oo53rlgvlcnjq foreign key (department_id) references departments;
